version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ytunhen
      POSTGRES_PASSWORD: 10040108Chuu
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  app:
    build: .
    depends_on:
      - db
      - kafka
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ytunhen
      DB_PASSWORD: 10040108Chuu
      DB_NAME: test
      KAFKA_BROKER: kafka:9092
